# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.4.0
group=com.kqp
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Improved Inventory Tabs
mod_author=KQP, LiamMCW, Andrew6rant (Andrew Grant), Jack Hair
archives_name=improved-inventory-tabs
mod_id=inventorytabs
license=MIT
description=Adds tabs to your inventory that lead to nearby blocks.
minecraft_version_range=[1.20.1, 1.20.2)

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html
forge_version=47.4.10
forge_loader_version_range=[47,)

# Dependencies
clothconfig_version=11.1.136
modmenu_version=7.2.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false
